### ISSUE TITLE
Migrate CI to Azure Pipelines

### ISSUE THREAD

**Issue by tabrath** [tabrath/BinaryEncoding#28]
Currently we're using Travis, Appveyor and CircleCI, which is making our builds more complex than we want. Azure Pipelines supports all the platforms that we want to support.

**Comment by hanabi1224** [comment]
I don't have too much experience with azure pipelines, appveyor seems good enough for me in terms of coverage (windows / ubuntu), build speed, preinstalled softwares (e.g. for mono repo that uses rust to build native code and then package into dotnet nuget).  What I dislike azure pipeline the most is, I find it hard (maybe I'm wrong) for others to setup own fork of CI pipeline if they want to make contributions to the yaml CI script, and because it has fancy web UI for manipulating the yaml CI script, it's not as readable as other CI config to me (maybe my bias tho)

**Comment by tabrath** [comment]
Can't say that I've got much experience myself, but after setting up a couple of pipelines it looks promising in my opinion. Support for windows, linux and mac is a bonus. The only reason for using both Appveyor and Travis was that Travis supports macOS, but it's terribly slow. Appveyor is pretty fast because it supports caching, which Azure has yet to implement (they've promised it will be available in the future).
As for the configuration of Azure Pipelines, you don't have to use the UI to manipulate it, just edit the yml file directly as with the other CI providers.
